### ISSUE TITLE
TableColumns with nested types

### ISSUE THREAD

**Issue by Fristi** [jatcwang/doobieroll#29]
```scala
case class Person(name: String, age: Int)
case class TestNested(parent: Person, child: Person, other: String)
```

Should expand with `TableColumns.deriveSnakeCaseTableColumns[TestNested]("test_nested")` to parent_name, parent_age, child_name, child_age, other

**Comment by jatcwang** [comment]
Hi @Fristi, I don't think this is as clearcut as the example you gave. What if `Person` maps to a JSON column?
The general principle this lib follows is that it should be clear what the resulting SQL is without digging into implementation.  

Can you tell me about the scenario you're trying to solve?

**Comment by Fristi** [comment]
In doobie when you construct a query you provide it's target type, in this case `TestNested`. Doobie will deconstruct this using shapeless in a product type to map this to the query. In this case it will be two phases:

```scala
Person :: Person :: String :: HNil // this maps to TestNested
```

Deconstruct it's product types

```
String :: Int :: String :: Int :: String :: HNil // String :: Int maps to Person
``` 

If I would use a query like `select parent_name, parent_age, child_name, child_age, other from table` this would work.

I am using this construct all the time to group coherent attributes into case classes.

**Comment by Fristi** [comment]
Basically it flattens the product type to heterogeneous list and conventionally I would like to prefix the attributes with wrapping field name

**Comment by jatcwang** [comment]
Sure, let's explore the possibility a bit.

Assuming that person is a table, I don't think this query is valid

```
select parent_name, parent_age, child_name, child_age, other from person left join person on /* find parent */
```

because you'd need field renaming such as `parent.name as parent_name`

Now, we could make our auto-derivation use `.` instead of `_`, but I at that point I think we'd be better off just doing something like this


```
val selectTestNestedColumns: Fragment = {
  import doobieroll.snippets._
  selectColumns(
    Person.columns.prefixed("parent"),
    Person.columns.prefixed("child"),
    fr"other"
  )
}

val actualQuery = {
  fr"""
    ${selectTestNestedColumns}
    FROM ...
    WHER ...
  """
}
```

Would that help you in this case?

(One issue I see with derivation as you suggested is that it's difficult to customize as you can't set a custom prefix for a particular field, so it ends up being less reuseable as well as being less approachable)

**Comment by Fristi** [comment]
The `Person` is not embedded in the same table so the query would be

```
select parent_name, parent_age, child_name, child_age, other from table
```

This works by default in doobie because flattening of the product types result in aforementioned heterogenous list type. 

I see your point about customizing, but for me using conventions works (also TableColumns now derives the names of the columns from the case class field names, so that's not difference)

**Comment by jatcwang** [comment]
I feel like it's very rare for a typical table to embed the same entity multiple times (such that you do not need field renaming like you're suggesting). I personally haven't seen it before and I feel like implementing this would make reasoning about the final SQL more difficult and surprising. (Imagine your new type case class suddenly gets translated to a different name than expected)

**Comment by Fristi** [comment]
Oke, let's close this one then
